// Lista de aeroportos: [IATA, Cidade, Nome do Aeroporto, País]
const AIRPORTS = [
  // ── Brasil — capitais e grandes hubs ─────────────────────────────────────
  ["GRU","São Paulo","Aeroporto Internacional de Guarulhos","Brasil"],
  ["CGH","São Paulo","Aeroporto de Congonhas","Brasil"],
  ["VCP","Campinas","Aeroporto Internacional de Viracopos","Brasil"],
  ["GIG","Rio de Janeiro","Aeroporto Internacional do Galeão","Brasil"],
  ["SDU","Rio de Janeiro","Aeroporto Santos Dumont","Brasil"],
  ["BSB","Brasília","Aeroporto Internacional de Brasília","Brasil"],
  ["SSA","Salvador","Aeroporto Internacional de Salvador","Brasil"],
  ["FOR","Fortaleza","Aeroporto Internacional Pinto Martins","Brasil"],
  ["REC","Recife","Aeroporto Internacional do Recife","Brasil"],
  ["MAO","Manaus","Aeroporto Internacional Eduardo Gomes","Brasil"],
  ["BEL","Belém","Aeroporto Internacional de Belém","Brasil"],
  ["POA","Porto Alegre","Aeroporto Internacional Salgado Filho","Brasil"],
  ["CWB","Curitiba","Aeroporto Internacional Afonso Pena","Brasil"],
  ["FLN","Florianópolis","Aeroporto Internacional Hercílio Luz","Brasil"],
  ["VIX","Vitória","Aeroporto de Vitória","Brasil"],
  ["CNF","Belo Horizonte","Aeroporto Internacional Confins","Brasil"],
  ["PLU","Belo Horizonte","Aeroporto da Pampulha","Brasil"],
  ["NAT","Natal","Aeroporto Internacional de São Gonçalo do Amarante","Brasil"],
  ["MCZ","Maceió","Aeroporto Internacional Zumbi dos Palmares","Brasil"],
  ["JPA","João Pessoa","Aeroporto Internacional Presidente Castro Pinto","Brasil"],
  ["THE","Teresina","Aeroporto Senador Petrônio Portella","Brasil"],
  ["SLZ","São Luís","Aeroporto Internacional Marechal Cunha Machado","Brasil"],
  ["AJU","Aracaju","Aeroporto Santa Maria","Brasil"],
  ["PMW","Palmas","Aeroporto de Palmas","Brasil"],
  ["CGB","Cuiabá","Aeroporto Internacional Marechal Rondon","Brasil"],
  ["CGR","Campo Grande","Aeroporto Internacional de Campo Grande","Brasil"],
  ["PVH","Porto Velho","Aeroporto Internacional Jorge Teixeira","Brasil"],
  ["RBR","Rio Branco","Aeroporto Internacional Plácido de Castro","Brasil"],
  ["MCP","Macapá","Aeroporto Internacional de Macapá","Brasil"],
  ["BVB","Boa Vista","Aeroporto Internacional Atlas Brasil Cantanhede","Brasil"],
  ["GYN","Goiânia","Aeroporto Santa Genoveva","Brasil"],

  // ── Brasil — Sul ──────────────────────────────────────────────────────────
  ["JOI","Joinville","Aeroporto de Joinville","Brasil"],
  ["NVT","Navegantes","Aeroporto de Navegantes","Brasil"],
  ["XAP","Chapecó","Aeroporto de Chapecó","Brasil"],
  ["IGU","Foz do Iguaçu","Aeroporto Internacional de Foz do Iguaçu","Brasil"],
  ["CXJ","Caxias do Sul","Aeroporto Hugo Cantergiani","Brasil"],
  ["PET","Pelotas","Aeroporto de Pelotas","Brasil"],
  ["URG","Uruguaiana","Aeroporto de Uruguaiana","Brasil"],
  ["BNU","Blumenau","Aeroporto de Blumenau","Brasil"],
  ["ITJ","Itajaí","Aeroporto de Itajaí","Brasil"],
  ["CCI","Concórdia","Aeroporto de Concórdia","Brasil"],
  ["JCB","Joaçaba","Aeroporto de Joaçaba","Brasil"],
  ["SBS","Joinville","Aeroporto de São Bento do Sul","Brasil"],
  ["PFB","Passo Fundo","Aeroporto de Passo Fundo","Brasil"],
  ["IJU","Ijuí","Aeroporto de Ijuí","Brasil"],
  ["SRA","Santa Rosa","Aeroporto de Santa Rosa","Brasil"],
  ["ERE","Erechim","Aeroporto de Erechim","Brasil"],
  ["ALQ","alegrete","Aeroporto de Alegrete","Brasil"],
  ["BGX","Bagé","Aeroporto de Bagé","Brasil"],
  ["RIG","Rio Grande","Aeroporto de Rio Grande","Brasil"],
  ["APX","Arapongas","Aeroporto de Arapongas","Brasil"],
  ["LDB","Londrina","Aeroporto de Londrina","Brasil"],
  ["MGF","Maringá","Aeroporto de Maringá","Brasil"],
  ["CAC","Cascavel","Aeroporto de Cascavel","Brasil"],
  ["FOZ","Foz do Iguaçu","Aeroporto de Foz do Iguaçu","Brasil"],
  ["PGZ","Ponta Grossa","Aeroporto de Ponta Grossa","Brasil"],
  ["GUJ","Guarapuava","Aeroporto de Guarapuava","Brasil"],
  ["CLV","Cornélio Procópio","Aeroporto de Cornélio Procópio","Brasil"],

  // ── Brasil — Sudeste ──────────────────────────────────────────────────────
  ["PPB","Presidente Prudente","Aeroporto de Presidente Prudente","Brasil"],
  ["RAO","Ribeirão Preto","Aeroporto de Ribeirão Preto","Brasil"],
  ["JTC","Bauru","Aeroporto de Bauru","Brasil"],
  ["SJK","São José dos Campos","Aeroporto de São José dos Campos","Brasil"],
  ["MII","Marília","Aeroporto de Marília","Brasil"],
  ["CAW","Campos dos Goytacazes","Aeroporto de Campos","Brasil"],
  ["GVR","Governador Valadares","Aeroporto de Governador Valadares","Brasil"],
  ["MOC","Montes Claros","Aeroporto de Montes Claros","Brasil"],
  ["IPN","Ipatinga","Aeroporto de Ipatinga","Brasil"],
  ["UDI","Uberlândia","Aeroporto de Uberlândia","Brasil"],
  ["SOD","Sorocaba","Aeroporto de Sorocaba","Brasil"],
  ["ARU","Araçatuba","Aeroporto de Araçatuba","Brasil"],
  ["AQA","Araraquara","Aeroporto de Araraquara","Brasil"],
  ["BAU","Bauru","Aeroporto de Bauru-Arealva","Brasil"],
  ["ITA","Itapetininga","Aeroporto de Itapetininga","Brasil"],
  ["OUS","Ourinhos","Aeroporto de Ourinhos","Brasil"],
  ["VOT","Votuporanga","Aeroporto de Votuporanga","Brasil"],
  ["QDV","Franca","Aeroporto de Franca","Brasil"],
  ["TBT","Tabatinga","Aeroporto Internacional de Tabatinga","Brasil"],
  ["NIT","Niterói","Aeroporto de Niterói","Brasil"],
  ["PMV","Petrópolis","Aeroporto de Petrópolis","Brasil"],
  ["SSZ","Santos","Aeroporto Base Aérea de Santos","Brasil"],
  ["QPS","Pindamonhangaba","Aeroporto de Pindamonhangaba","Brasil"],
  ["DIQ","Divinópolis","Aeroporto de Divinópolis","Brasil"],
  ["JDF","Juiz de Fora","Aeroporto de Juiz de Fora","Brasil"],
  ["VAG","Varginha","Aeroporto de Varginha","Brasil"],
  ["UBA","Uberaba","Aeroporto de Uberaba","Brasil"],
  ["PCL","Patos de Minas","Aeroporto de Patos de Minas","Brasil"],
  ["BZC","Búzios","Aeroporto de Búzios","Brasil"],
  ["QNV","Nova Friburgo","Aeroporto de Nova Friburgo","Brasil"],

  // ── Brasil — Nordeste ─────────────────────────────────────────────────────
  ["IOS","Ilhéus","Aeroporto de Ilhéus","Brasil"],
  ["BPS","Porto Seguro","Aeroporto de Porto Seguro","Brasil"],
  ["FEC","Feira de Santana","Aeroporto de Feira de Santana","Brasil"],
  ["PAV","Paulo Afonso","Aeroporto de Paulo Afonso","Brasil"],
  ["PHB","Parnaíba","Aeroporto de Parnaíba","Brasil"],
  ["JDO","Juazeiro do Norte","Aeroporto de Juazeiro do Norte","Brasil"],
  ["MOS","Mossoró","Aeroporto de Mossoró","Brasil"],
  ["CPV","Campina Grande","Aeroporto de Campina Grande","Brasil"],
  ["PNZ","Petrolina","Aeroporto de Petrolina","Brasil"],
  ["QCN","Canindé","Aeroporto de Canindé","Brasil"],
  ["SFK","Soure","Aeroporto de Soure","Brasil"],
  ["TUR","Tucuruí","Aeroporto de Tucuruí","Brasil"],
  ["VDC","Vitória da Conquista","Aeroporto de Vitória da Conquista","Brasil"],
  ["BMS","Brumado","Aeroporto de Brumado","Brasil"],
  ["BQQ","Barra","Aeroporto de Barra","Brasil"],
  ["PIV","Pirapora","Aeroporto de Pirapora","Brasil"],
  ["SXX","São Félix do Xingu","Aeroporto de São Félix do Xingu","Brasil"],
  ["CAF","Carauari","Aeroporto de Carauari","Brasil"],
  ["ATM","Altamira","Aeroporto de Altamira","Brasil"],
  ["OBI","Óbidos","Aeroporto de Óbidos","Brasil"],
  ["MAB","Marabá","Aeroporto de Marabá","Brasil"],
  ["IMP","Imperatriz","Aeroporto de Imperatriz","Brasil"],
  ["PIN","Parintins","Aeroporto de Parintins","Brasil"],
  ["BCR","Boca do Acre","Aeroporto de Boca do Acre","Brasil"],
  ["ERN","Eirunepé","Aeroporto de Eirunepé","Brasil"],

  // ── Brasil — Centro-Oeste & Norte ─────────────────────────────────────────
  ["STM","Santarém","Aeroporto de Santarém","Brasil"],
  ["OPS","Sinop","Aeroporto de Sinop","Brasil"],
  ["ROO","Rondonópolis","Aeroporto de Rondonópolis","Brasil"],
  ["AUX","Araguaína","Aeroporto de Araguaína","Brasil"],
  ["PMG","Ponta Porã","Aeroporto de Ponta Porã","Brasil"],
  ["TFF","Tefé","Aeroporto de Tefé","Brasil"],
  ["MNX","Manicoré","Aeroporto de Manicoré","Brasil"],
  ["JIA","Juína","Aeroporto de Juína","Brasil"],
  ["CMG","Corumbá","Aeroporto de Corumbá","Brasil"],
  ["TJL","Três Lagoas","Aeroporto de Três Lagoas","Brasil"],
  ["APQ","Arapiraca","Aeroporto de Arapiraca","Brasil"],
  ["GNM","Guanambi","Aeroporto de Guanambi","Brasil"],
  ["BHV","Barreiras","Aeroporto de Barreiras","Brasil"],
  ["LEC","Lençóis","Aeroporto de Lençóis","Brasil"],
  ["MVF","Mossoró","Aeroporto Dix-Sept Rosado","Brasil"],
  ["JJD","Jijoca de Jericoacoara","Aeroporto de Jericoacoara","Brasil"],
  ["FBA","Fonte Boa","Aeroporto de Fonte Boa","Brasil"],
  ["AJU","Aracaju","Aeroporto Santa Maria","Brasil"],
  ["GUJ","Guarapuava","Aeroporto de Guarapuava","Brasil"],

  // ── América do Sul ────────────────────────────────────────────────────────
  ["EZE","Buenos Aires","Aeroporto Internacional Ezeiza","Argentina"],
  ["AEP","Buenos Aires","Aeroporto Metropolitano Jorge Newbery","Argentina"],
  ["COR","Córdoba","Aeroporto Internacional de Córdoba","Argentina"],
  ["MDZ","Mendoza","Aeroporto Internacional de Mendoza","Argentina"],
  ["BRC","Bariloche","Aeroporto Internacional de Bariloche","Argentina"],
  ["ROS","Rosário","Aeroporto Internacional de Rosário","Argentina"],
  ["SLA","Salta","Aeroporto Internacional de Salta","Argentina"],
  ["TUC","Tucumán","Aeroporto Internacional de Tucumán","Argentina"],
  ["IGR","Puerto Iguazú","Aeroporto Internacional de Puerto Iguazú","Argentina"],
  ["NQN","Neuquén","Aeroporto Internacional de Neuquén","Argentina"],
  ["USH","Ushuaia","Aeroporto Internacional de Ushuaia","Argentina"],
  ["FTE","El Calafate","Aeroporto Internacional de El Calafate","Argentina"],
  ["SCL","Santiago","Aeroporto Internacional Arturo Merino Benítez","Chile"],
  ["PMC","Puerto Montt","Aeroporto Internacional El Tepual","Chile"],
  ["IQQ","Iquique","Aeroporto Internacional Diego Aracena","Chile"],
  ["ANF","Antofagasta","Aeroporto Internacional Andrés Sabella","Chile"],
  ["CJC","Calama","Aeroporto Internacional El Loa","Chile"],
  ["SCL","Santiago","Aeroporto Internacional Arturo Merino Benítez","Chile"],
  ["ZCO","Temuco","Aeroporto Internacional La Araucanía","Chile"],
  ["PMC","Puerto Montt","Aeroporto El Tepual","Chile"],
  ["LIM","Lima","Aeroporto Internacional Jorge Chávez","Peru"],
  ["CUZ","Cusco","Aeroporto Internacional Alejandro Velasco Astete","Peru"],
  ["AQP","Arequipa","Aeroporto Internacional Rodríguez Ballón","Peru"],
  ["IQT","Iquitos","Aeroporto Internacional Francisco Secada Vignetta","Peru"],
  ["BOG","Bogotá","Aeroporto Internacional El Dorado","Colômbia"],
  ["MDE","Medellín","Aeroporto Internacional José María Córdova","Colômbia"],
  ["CLO","Cali","Aeroporto Internacional Alfonso Bonilla Aragón","Colômbia"],
  ["CTG","Cartagena","Aeroporto Internacional Rafael Núñez","Colômbia"],
  ["BAQ","Barranquilla","Aeroporto Internacional Ernesto Cortissoz","Colômbia"],
  ["UIO","Quito","Aeroporto Internacional Mariscal Sucre","Equador"],
  ["GYE","Guayaquil","Aeroporto Internacional José Joaquín de Olmedo","Equador"],
  ["GPS","Galápagos","Aeroporto Seymour","Equador"],
  ["MVD","Montevidéu","Aeroporto Internacional de Carrasco","Uruguai"],
  ["PDP","Punta del Este","Aeroporto Internacional de Punta del Este","Uruguai"],
  ["ASU","Assunção","Aeroporto Internacional Silvio Pettirossi","Paraguai"],
  ["CIO","Ciudad del Este","Aeroporto Internacional de Ciudad del Este","Paraguai"],
  ["LPB","La Paz","Aeroporto Internacional El Alto","Bolívia"],
  ["VVI","Santa Cruz","Aeroporto Internacional Viru Viru","Bolívia"],
  ["CBB","Cochabamba","Aeroporto Internacional Jorge Wilstermann","Bolívia"],
  ["CCS","Caracas","Aeroporto Internacional Simón Bolívar","Venezuela"],
  ["MAR","Maracaibo","Aeroporto Internacional La Chinita","Venezuela"],
  ["GEO","Georgetown","Aeroporto Internacional Cheddi Jagan","Guiana"],
  ["PBM","Paramaribo","Aeroporto Internacional Johan Adolf Pengel","Suriname"],
  ["CAY","Caiena","Aeroporto Internacional Félix Eboué","Guiana Francesa"],

  // ── América do Norte — EUA ────────────────────────────────────────────────
  ["JFK","Nova York","Aeroporto Internacional John F. Kennedy","EUA"],
  ["EWR","Newark","Aeroporto Internacional de Newark","EUA"],
  ["LGA","Nova York","Aeroporto LaGuardia","EUA"],
  ["MIA","Miami","Aeroporto Internacional de Miami","EUA"],
  ["FLL","Fort Lauderdale","Aeroporto Internacional de Fort Lauderdale","EUA"],
  ["LAX","Los Angeles","Aeroporto Internacional de Los Angeles","EUA"],
  ["SNA","Orange County","Aeroporto Internacional John Wayne","EUA"],
  ["BUR","Burbank","Aeroporto Bob Hope","EUA"],
  ["LGB","Long Beach","Aeroporto de Long Beach","EUA"],
  ["ORD","Chicago","Aeroporto Internacional O'Hare","EUA"],
  ["MDW","Chicago","Aeroporto Midway","EUA"],
  ["ATL","Atlanta","Aeroporto Internacional Hartsfield-Jackson","EUA"],
  ["DFW","Dallas","Aeroporto Internacional Dallas/Fort Worth","EUA"],
  ["DAL","Dallas","Aeroporto Love Field","EUA"],
  ["IAH","Houston","Aeroporto Internacional George Bush","EUA"],
  ["HOU","Houston","Aeroporto Hobby","EUA"],
  ["DEN","Denver","Aeroporto Internacional de Denver","EUA"],
  ["SFO","San Francisco","Aeroporto Internacional de San Francisco","EUA"],
  ["OAK","Oakland","Aeroporto Internacional de Oakland","EUA"],
  ["SJC","San Jose","Aeroporto Internacional de San Jose","EUA"],
  ["SEA","Seattle","Aeroporto Internacional Seattle-Tacoma","EUA"],
  ["LAS","Las Vegas","Aeroporto Internacional Harry Reid","EUA"],
  ["PHX","Phoenix","Aeroporto Internacional Sky Harbor","EUA"],
  ["TUS","Tucson","Aeroporto Internacional de Tucson","EUA"],
  ["MCO","Orlando","Aeroporto Internacional de Orlando","EUA"],
  ["TPA","Tampa","Aeroporto Internacional de Tampa","EUA"],
  ["PIE","St. Petersburg","Aeroporto Internacional St. Pete-Clearwater","EUA"],
  ["RSW","Fort Myers","Aeroporto Internacional Southwest Florida","EUA"],
  ["PBI","West Palm Beach","Aeroporto Internacional de Palm Beach","EUA"],
  ["MKE","Milwaukee","Aeroporto Internacional Mitchell","EUA"],
  ["BOS","Boston","Aeroporto Internacional Logan","EUA"],
  ["IAD","Washington","Aeroporto Internacional Dulles","EUA"],
  ["DCA","Washington","Aeroporto Ronald Reagan","EUA"],
  ["BWI","Baltimore","Aeroporto Internacional Baltimore/Washington","EUA"],
  ["CLT","Charlotte","Aeroporto Internacional Douglas","EUA"],
  ["DTW","Detroit","Aeroporto Internacional Detroit Metropolitan","EUA"],
  ["MSP","Minneapolis","Aeroporto Internacional Minneapolis-Saint Paul","EUA"],
  ["PHL","Filadélfia","Aeroporto Internacional de Filadélfia","EUA"],
  ["PIT","Pittsburgh","Aeroporto Internacional de Pittsburgh","EUA"],
  ["CLE","Cleveland","Aeroporto Internacional Hopkins","EUA"],
  ["CMH","Columbus","Aeroporto Internacional de Columbus","EUA"],
  ["IND","Indianapolis","Aeroporto Internacional de Indianapolis","EUA"],
  ["STL","St. Louis","Aeroporto Internacional Lambert","EUA"],
  ["MSY","Nova Orleans","Aeroporto Internacional Louis Armstrong","EUA"],
  ["MEM","Memphis","Aeroporto Internacional de Memphis","EUA"],
  ["BNA","Nashville","Aeroporto Internacional de Nashville","EUA"],
  ["SDF","Louisville","Aeroporto Internacional de Louisville","EUA"],
  ["ORF","Norfolk","Aeroporto Internacional de Norfolk","EUA"],
  ["RIC","Richmond","Aeroporto Internacional de Richmond","EUA"],
  ["RDU","Raleigh","Aeroporto Internacional Raleigh-Durham","EUA"],
  ["GSO","Greensboro","Aeroporto Internacional Piedmont Triad","EUA"],
  ["CHS","Charleston","Aeroporto Internacional de Charleston","EUA"],
  ["SAV","Savannah","Aeroporto Internacional de Savannah","EUA"],
  ["JAX","Jacksonville","Aeroporto Internacional de Jacksonville","EUA"],
  ["SRQ","Sarasota","Aeroporto Internacional de Sarasota","EUA"],
  ["PWM","Portland ME","Aeroporto Internacional de Portland","EUA"],
  ["BTV","Burlington","Aeroporto Internacional de Burlington","EUA"],
  ["ALB","Albany","Aeroporto Internacional de Albany","EUA"],
  ["SYR","Syracuse","Aeroporto Internacional Hancock","EUA"],
  ["ROC","Rochester","Aeroporto Internacional de Rochester","EUA"],
  ["BUF","Buffalo","Aeroporto Internacional Niagara","EUA"],
  ["PDX","Portland OR","Aeroporto Internacional de Portland","EUA"],
  ["BOI","Boise","Aeroporto Internacional de Boise","EUA"],
  ["SLC","Salt Lake City","Aeroporto Internacional de Salt Lake City","EUA"],
  ["ABQ","Albuquerque","Aeroporto Internacional de Albuquerque","EUA"],
  ["OKC","Oklahoma City","Aeroporto Internacional Will Rogers","EUA"],
  ["TUL","Tulsa","Aeroporto Internacional de Tulsa","EUA"],
  ["SAT","San Antonio","Aeroporto Internacional de San Antonio","EUA"],
  ["AUS","Austin","Aeroporto Internacional Austin-Bergstrom","EUA"],
  ["ELP","El Paso","Aeroporto Internacional de El Paso","EUA"],
  ["ONT","Ontario","Aeroporto Internacional de Ontario","EUA"],
  ["SAN","San Diego","Aeroporto Internacional de San Diego","EUA"],
  ["SMF","Sacramento","Aeroporto Internacional de Sacramento","EUA"],
  ["RNO","Reno","Aeroporto Internacional de Reno","EUA"],
  ["FAI","Fairbanks","Aeroporto Internacional de Fairbanks","EUA"],
  ["ANC","Anchorage","Aeroporto Internacional Ted Stevens","EUA"],
  ["HNL","Honolulu","Aeroporto Internacional Daniel K. Inouye","EUA"],
  ["OGG","Maui","Aeroporto de Kahului","EUA"],
  ["KOA","Kona","Aeroporto Internacional de Kona","EUA"],
  ["LIH","Kauai","Aeroporto de Lihue","EUA"],

  // ── América do Norte — Canadá ─────────────────────────────────────────────
  ["YYZ","Toronto","Aeroporto Internacional Pearson","Canadá"],
  ["YYC","Calgary","Aeroporto Internacional de Calgary","Canadá"],
  ["YUL","Montreal","Aeroporto Internacional Pierre Elliott Trudeau","Canadá"],
  ["YVR","Vancouver","Aeroporto Internacional de Vancouver","Canadá"],
  ["YEG","Edmonton","Aeroporto Internacional de Edmonton","Canadá"],
  ["YOW","Ottawa","Aeroporto Internacional de Ottawa","Canadá"],
  ["YHZ","Halifax","Aeroporto Internacional Stanfield","Canadá"],
  ["YWG","Winnipeg","Aeroporto Internacional de Winnipeg","Canadá"],
  ["YQB","Quebec","Aeroporto Internacional Jean Lesage","Canadá"],
  ["YYJ","Victoria","Aeroporto Internacional de Victoria","Canadá"],
  ["YXE","Saskatoon","Aeroporto Internacional de Saskatoon","Canadá"],
  ["YQR","Regina","Aeroporto Internacional de Regina","Canadá"],

  // ── América do Norte — México e América Central ───────────────────────────
  ["MEX","Cidade do México","Aeroporto Internacional Benito Juárez","México"],
  ["NLU","Cidade do México","Aeroporto Internacional Felipe Ángeles","México"],
  ["CUN","Cancún","Aeroporto Internacional de Cancún","México"],
  ["GDL","Guadalajara","Aeroporto Internacional Miguel Hidalgo","México"],
  ["MTY","Monterrey","Aeroporto Internacional General Mariano Escobedo","México"],
  ["SJD","Los Cabos","Aeroporto Internacional de Los Cabos","México"],
  ["PVR","Puerto Vallarta","Aeroporto Internacional Licenciado Gustavo Díaz Ordaz","México"],
  ["MZT","Mazatlán","Aeroporto Internacional Rafael Buelna","México"],
  ["HMO","Hermosillo","Aeroporto Internacional de Hermosillo","México"],
  ["TIJ","Tijuana","Aeroporto Internacional de Tijuana","México"],
  ["OAX","Oaxaca","Aeroporto Internacional de Oaxaca","México"],
  ["MID","Mérida","Aeroporto Internacional de Mérida","México"],
  ["VER","Veracruz","Aeroporto Internacional de Veracruz","México"],
  ["AGU","Aguascalientes","Aeroporto Internacional de Aguascalientes","México"],
  ["PTY","Cidade do Panamá","Aeroporto Internacional de Tocumen","Panamá"],
  ["SJO","San José","Aeroporto Internacional Juan Santamaría","Costa Rica"],
  ["LIR","Liberia","Aeroporto Internacional Daniel Oduber","Costa Rica"],
  ["GUA","Guatemala","Aeroporto Internacional La Aurora","Guatemala"],
  ["SAP","San Pedro Sula","Aeroporto Internacional Ramón Villeda Morales","Honduras"],
  ["TGU","Tegucigalpa","Aeroporto Internacional Toncontín","Honduras"],
  ["MGA","Manágua","Aeroporto Internacional de Manágua","Nicarágua"],
  ["SAL","San Salvador","Aeroporto Internacional Monseñor Óscar Romero","El Salvador"],
  ["HAV","Havana","Aeroporto Internacional José Martí","Cuba"],
  ["SDQ","Santo Domingo","Aeroporto Internacional Las Américas","República Dominicana"],
  ["PUJ","Punta Cana","Aeroporto Internacional de Punta Cana","República Dominicana"],
  ["SJU","San Juan","Aeroporto Internacional Luis Muñoz Marín","Porto Rico"],
  ["BGI","Bridgetown","Aeroporto Internacional Grantley Adams","Barbados"],
  ["POS","Port of Spain","Aeroporto Internacional Piarco","Trinidad e Tobago"],
  ["NAS","Nassau","Aeroporto Internacional Lynden Pindling","Bahamas"],
  ["AUA","Oranjestad","Aeroporto Internacional Reina Beatrix","Aruba"],
  ["CUR","Willemstad","Aeroporto Internacional Hato","Curaçao"],
  ["JAM","Montego Bay","Aeroporto Internacional Sangster","Jamaica"],
  ["KIN","Kingston","Aeroporto Internacional Norman Manley","Jamaica"],
  ["GCM","Grand Cayman","Aeroporto Internacional Owen Roberts","Ilhas Cayman"],

  // ── Europa — Ilhas Britânicas ─────────────────────────────────────────────
  ["LHR","Londres","Aeroporto de Heathrow","Reino Unido"],
  ["LGW","Londres","Aeroporto de Gatwick","Reino Unido"],
  ["STN","Londres","Aeroporto de Stansted","Reino Unido"],
  ["LTN","Londres","Aeroporto de Luton","Reino Unido"],
  ["LCY","Londres","Aeroporto de London City","Reino Unido"],
  ["MAN","Manchester","Aeroporto de Manchester","Reino Unido"],
  ["BHX","Birmingham","Aeroporto de Birmingham","Reino Unido"],
  ["GLA","Glasgow","Aeroporto de Glasgow","Reino Unido"],
  ["EDI","Edimburgo","Aeroporto de Edimburgo","Reino Unido"],
  ["BFS","Belfast","Aeroporto Internacional de Belfast","Reino Unido"],
  ["NCL","Newcastle","Aeroporto Internacional de Newcastle","Reino Unido"],
  ["LBA","Leeds","Aeroporto de Leeds Bradford","Reino Unido"],
  ["BRS","Bristol","Aeroporto de Bristol","Reino Unido"],
  ["DUB","Dublin","Aeroporto de Dublin","Irlanda"],
  ["ORK","Cork","Aeroporto de Cork","Irlanda"],
  ["SNN","Shannon","Aeroporto de Shannon","Irlanda"],

  // ── Europa — França ───────────────────────────────────────────────────────
  ["CDG","Paris","Aeroporto Charles de Gaulle","França"],
  ["ORY","Paris","Aeroporto de Orly","França"],
  ["LYS","Lyon","Aeroporto de Lyon-Saint Exupéry","França"],
  ["MRS","Marselha","Aeroporto de Marselha","França"],
  ["NCE","Nice","Aeroporto Côte d'Azur","França"],
  ["TLS","Toulouse","Aeroporto de Blagnac","França"],
  ["BOD","Bordeaux","Aeroporto de Bordeaux-Mérignac","França"],
  ["NTE","Nantes","Aeroporto Atlantique","França"],
  ["SXB","Estrasburgo","Aeroporto de Estrasburgo","França"],
  ["MPL","Montpellier","Aeroporto de Montpellier","França"],

  // ── Europa — Alemanha ─────────────────────────────────────────────────────
  ["FRA","Frankfurt","Aeroporto de Frankfurt","Alemanha"],
  ["MUC","Munique","Aeroporto Internacional de Munique","Alemanha"],
  ["BER","Berlim","Aeroporto de Berlim Brandenburgo","Alemanha"],
  ["DUS","Düsseldorf","Aeroporto de Düsseldorf","Alemanha"],
  ["HAM","Hamburgo","Aeroporto de Hamburgo","Alemanha"],
  ["CGN","Colônia","Aeroporto de Colônia/Bonn","Alemanha"],
  ["STR","Stuttgart","Aeroporto de Stuttgart","Alemanha"],
  ["NUE","Nuremberg","Aeroporto de Nuremberg","Alemanha"],
  ["LEJ","Leipzig","Aeroporto de Leipzig/Halle","Alemanha"],
  ["HAJ","Hanover","Aeroporto de Hanover","Alemanha"],
  ["BRE","Bremen","Aeroporto de Bremen","Alemanha"],

  // ── Europa — Península Ibérica ────────────────────────────────────────────
  ["MAD","Madri","Aeroporto Adolfo Suárez Barajas","Espanha"],
  ["BCN","Barcelona","Aeroporto de El Prat","Espanha"],
  ["AGP","Málaga","Aeroporto de Málaga","Espanha"],
  ["PMI","Palma de Mallorca","Aeroporto de Palma de Mallorca","Espanha"],
  ["ALC","Alicante","Aeroporto de Alicante","Espanha"],
  ["VLC","Valência","Aeroporto de Valência","Espanha"],
  ["SVQ","Sevilha","Aeroporto de Sevilha","Espanha"],
  ["BIO","Bilbao","Aeroporto de Bilbao","Espanha"],
  ["TFN","Tenerife","Aeroporto de Tenerife Norte","Espanha"],
  ["TFS","Tenerife","Aeroporto de Tenerife Sul","Espanha"],
  ["LPA","Las Palmas","Aeroporto de Gran Canaria","Espanha"],
  ["IBZ","Ibiza","Aeroporto de Ibiza","Espanha"],
  ["LIS","Lisboa","Aeroporto Internacional Humberto Delgado","Portugal"],
  ["OPO","Porto","Aeroporto Francisco Sá Carneiro","Portugal"],
  ["FAO","Faro","Aeroporto de Faro","Portugal"],
  ["FNC","Funchal","Aeroporto Internacional da Madeira","Portugal"],
  ["PDL","Ponta Delgada","Aeroporto Internacional João Paulo II","Portugal"],

  // ── Europa — Itália ───────────────────────────────────────────────────────
  ["FCO","Roma","Aeroporto Internacional de Fiumicino","Itália"],
  ["CIA","Roma","Aeroporto de Ciampino","Itália"],
  ["MXP","Milão","Aeroporto Internacional de Malpensa","Itália"],
  ["LIN","Milão","Aeroporto de Linate","Itália"],
  ["BGY","Milão","Aeroporto de Bérgamo","Itália"],
  ["VCE","Veneza","Aeroporto Marco Polo","Itália"],
  ["NAP","Nápoles","Aeroporto Internacional de Nápoles","Itália"],
  ["BLQ","Bolonha","Aeroporto Guglielmo Marconi","Itália"],
  ["FLR","Florença","Aeroporto Amerigo Vespucci","Itália"],
  ["PSA","Pisa","Aeroporto Galileo Galilei","Itália"],
  ["CTA","Catânia","Aeroporto de Fontanarossa","Itália"],
  ["PMO","Palermo","Aeroporto Falcone Borsellino","Itália"],

  // ── Europa — Outros ───────────────────────────────────────────────────────
  ["AMS","Amsterdã","Aeroporto de Schiphol","Holanda"],
  ["EIN","Eindhoven","Aeroporto de Eindhoven","Holanda"],
  ["ZRH","Zurique","Aeroporto de Zurique","Suíça"],
  ["GVA","Genebra","Aeroporto Internacional de Genebra","Suíça"],
  ["BSL","Basileia","Aeroporto Euro-Airport Basileia","Suíça"],
  ["BRU","Bruxelas","Aeroporto de Bruxelas","Bélgica"],
  ["CRL","Charleroi","Aeroporto de Charleroi","Bélgica"],
  ["VIE","Viena","Aeroporto Internacional de Viena","Áustria"],
  ["GRZ","Graz","Aeroporto de Graz","Áustria"],
  ["SZG","Salzburgo","Aeroporto de Salzburgo","Áustria"],
  ["CPH","Copenhague","Aeroporto de Copenhague","Dinamarca"],
  ["ARN","Estocolmo","Aeroporto de Arlanda","Suécia"],
  ["GOT","Gotemburgo","Aeroporto de Landvetter","Suécia"],
  ["MMX","Malmö","Aeroporto de Malmö","Suécia"],
  ["OSL","Oslo","Aeroporto de Gardermoen","Noruega"],
  ["BGO","Bergen","Aeroporto de Flesland","Noruega"],
  ["SVG","Stavanger","Aeroporto de Sola","Noruega"],
  ["TRD","Trondheim","Aeroporto de Trondheim","Noruega"],
  ["HEL","Helsinque","Aeroporto de Vantaa","Finlândia"],
  ["TMP","Tampere","Aeroporto de Tampere","Finlândia"],
  ["WAW","Varsóvia","Aeroporto Chopin","Polônia"],
  ["KRK","Cracóvia","Aeroporto Internacional João Paulo II","Polônia"],
  ["WRO","Breslávia","Aeroporto de Breslávia","Polônia"],
  ["GDN","Gdansk","Aeroporto de Gdansk","Polônia"],
  ["PRG","Praga","Aeroporto Václav Havel","Rep. Tcheca"],
  ["BRQ","Brno","Aeroporto de Brno","Rep. Tcheca"],
  ["BUD","Budapeste","Aeroporto Internacional de Budapeste","Hungria"],
  ["OTP","Bucareste","Aeroporto Internacional Henri Coandă","Romênia"],
  ["CLJ","Cluj-Napoca","Aeroporto Internacional de Cluj","Romênia"],
  ["SOF","Sofia","Aeroporto Internacional de Sofia","Bulgária"],
  ["ATH","Atenas","Aeroporto Internacional Elefthérios Venizélos","Grécia"],
  ["SKG","Thessaloniki","Aeroporto Makedonia","Grécia"],
  ["HER","Heraklion","Aeroporto Internacional de Heraklion","Grécia"],
  ["RHO","Rodes","Aeroporto Internacional de Rodes","Grécia"],
  ["CFU","Corfu","Aeroporto Internacional de Corfu","Grécia"],
  ["JMK","Mykonos","Aeroporto de Mykonos","Grécia"],
  ["JTR","Santorini","Aeroporto de Santorini","Grécia"],
  ["IST","Istambul","Aeroporto Internacional de Istambul","Turquia"],
  ["SAW","Istambul","Aeroporto de Sabiha Gökçen","Turquia"],
  ["AYT","Antalya","Aeroporto Internacional de Antalya","Turquia"],
  ["ADB","Izmir","Aeroporto Internacional Adnan Menderes","Turquia"],
  ["ESB","Ancara","Aeroporto Internacional Esenboğa","Turquia"],
  ["LJU","Ljubljana","Aeroporto de Ljubljana","Eslovênia"],
  ["ZAG","Zagreb","Aeroporto de Zagreb","Croácia"],
  ["SPU","Split","Aeroporto de Split","Croácia"],
  ["DBV","Dubrovnik","Aeroporto de Dubrovnik","Croácia"],
  ["BEG","Belgrado","Aeroporto de Belgrado","Sérvia"],
  ["SKP","Skopje","Aeroporto de Skopje","Macedônia do Norte"],
  ["TIA","Tirana","Aeroporto Internacional Nënë Tereza","Albânia"],
  ["OHD","Ohrid","Aeroporto de Ohrid","Macedônia do Norte"],
  ["RIX","Riga","Aeroporto Internacional de Riga","Letônia"],
  ["TLL","Tallinn","Aeroporto de Tallinn","Estônia"],
  ["VNO","Vilnius","Aeroporto Internacional de Vilnius","Lituânia"],
  ["HEL","Helsinque","Aeroporto de Vantaa","Finlândia"],
  ["KBP","Kiev","Aeroporto Internacional de Boryspil","Ucrânia"],
  ["SVO","Moscou","Aeroporto Internacional Sheremetyevo","Rússia"],
  ["DME","Moscou","Aeroporto Internacional Domodedovo","Rússia"],
  ["LED","São Petersburgo","Aeroporto de Pulkovo","Rússia"],
  ["KZN","Kazan","Aeroporto Internacional de Kazan","Rússia"],
  ["SVX","Yekaterinburg","Aeroporto de Koltsovo","Rússia"],
  ["OVB","Novosibirsk","Aeroporto de Tolmachevo","Rússia"],
  ["IKT","Irkutsk","Aeroporto de Irkutsk","Rússia"],
  ["VKO","Moscou","Aeroporto Internacional de Vnukovo","Rússia"],
  ["FCO","Roma","Aeroporto Internacional de Fiumicino","Itália"],

  // ── Oriente Médio ─────────────────────────────────────────────────────────
  ["DXB","Dubai","Aeroporto Internacional de Dubai","Emirados Árabes"],
  ["AUH","Abu Dhabi","Aeroporto Internacional de Abu Dhabi","Emirados Árabes"],
  ["SHJ","Sharjah","Aeroporto Internacional de Sharjah","Emirados Árabes"],
  ["DOH","Doha","Aeroporto Internacional de Hamad","Catar"],
  ["BAH","Manama","Aeroporto Internacional de Bahrein","Bahrein"],
  ["KWI","Kuwait","Aeroporto Internacional do Kuwait","Kuwait"],
  ["MCT","Mascate","Aeroporto Internacional de Mascate","Omã"],
  ["RUH","Riade","Aeroporto Internacional King Khalid","Arábia Saudita"],
  ["JED","Jidá","Aeroporto Internacional King Abdulaziz","Arábia Saudita"],
  ["DMM","Dammam","Aeroporto Internacional King Fahd","Arábia Saudita"],
  ["MED","Medina","Aeroporto Internacional Prince Mohammad bin Abdulaziz","Arábia Saudita"],
  ["TLV","Tel Aviv","Aeroporto Internacional Ben Gurion","Israel"],
  ["AMM","Amã","Aeroporto Internacional Queen Alia","Jordânia"],
  ["BGW","Bagdá","Aeroporto Internacional de Bagdá","Iraque"],
  ["TBZ","Tabriz","Aeroporto Internacional de Tabriz","Irã"],
  ["IKA","Teerã","Aeroporto Internacional Imam Khomeini","Irã"],
  ["BEY","Beirute","Aeroporto Internacional Rafic Hariri","Líbano"],
  ["DAM","Damasco","Aeroporto Internacional de Damasco","Síria"],

  // ── Ásia ──────────────────────────────────────────────────────────────────
  ["SIN","Singapura","Aeroporto de Changi","Singapura"],
  ["HKG","Hong Kong","Aeroporto Internacional de Hong Kong","Hong Kong"],
  ["NRT","Tóquio","Aeroporto Internacional de Narita","Japão"],
  ["HND","Tóquio","Aeroporto de Haneda","Japão"],
  ["KIX","Osaka","Aeroporto Internacional de Kansai","Japão"],
  ["ITM","Osaka","Aeroporto de Itami","Japão"],
  ["NGO","Nagoya","Aeroporto Internacional de Chubu","Japão"],
  ["CTS","Sapporo","Aeroporto Internacional de New Chitose","Japão"],
  ["FUK","Fukuoka","Aeroporto de Fukuoka","Japão"],
  ["OKA","Okinawa","Aeroporto Internacional de Naha","Japão"],
  ["ICN","Seul","Aeroporto Internacional de Incheon","Coreia do Sul"],
  ["GMP","Seul","Aeroporto de Gimpo","Coreia do Sul"],
  ["PUS","Busan","Aeroporto Internacional de Gimhae","Coreia do Sul"],
  ["PEK","Pequim","Aeroporto Internacional Capital","China"],
  ["PKX","Pequim","Aeroporto Internacional Daxing","China"],
  ["PVG","Xangai","Aeroporto Internacional de Pudong","China"],
  ["SHA","Xangai","Aeroporto de Hongqiao","China"],
  ["CAN","Guangzhou","Aeroporto Internacional Baiyun","China"],
  ["SZX","Shenzhen","Aeroporto Internacional de Bao'an","China"],
  ["CTU","Chengdu","Aeroporto Internacional de Shuangliu","China"],
  ["KMG","Kunming","Aeroporto Internacional de Changshui","China"],
  ["WUH","Wuhan","Aeroporto Internacional de Tianhe","China"],
  ["XIY","Xi'an","Aeroporto Internacional de Xianyang","China"],
  ["CKG","Chongqing","Aeroporto Internacional de Jiangbei","China"],
  ["HRB","Harbin","Aeroporto Internacional de Harbin","China"],
  ["TAO","Qingdao","Aeroporto Internacional de Qingdao","China"],
  ["BOM","Mumbai","Aeroporto Internacional Chhatrapati Shivaji","Índia"],
  ["DEL","Nova Delhi","Aeroporto Internacional Indira Gandhi","Índia"],
  ["BLR","Bengaluru","Aeroporto Internacional Kempegowda","Índia"],
  ["MAA","Chennai","Aeroporto Internacional de Chennai","Índia"],
  ["HYD","Hyderabad","Aeroporto Internacional Rajiv Gandhi","Índia"],
  ["CCU","Kolkata","Aeroporto Internacional Netaji Subhas Chandra Bose","Índia"],
  ["AMD","Ahmedabad","Aeroporto Internacional Sardar Vallabhbhai Patel","Índia"],
  ["COK","Kochi","Aeroporto Internacional de Cochin","Índia"],
  ["GOI","Goa","Aeroporto Internacional de Goa","Índia"],
  ["BKK","Bangkok","Aeroporto Internacional Suvarnabhumi","Tailândia"],
  ["DMK","Bangkok","Aeroporto Internacional Don Mueang","Tailândia"],
  ["HKT","Phuket","Aeroporto Internacional de Phuket","Tailândia"],
  ["CNX","Chiang Mai","Aeroporto Internacional de Chiang Mai","Tailândia"],
  ["KUL","Kuala Lumpur","Aeroporto Internacional de Kuala Lumpur","Malásia"],
  ["SZB","Kuala Lumpur","Aeroporto Internacional Sultan Abdul Aziz Shah","Malásia"],
  ["PEN","Penang","Aeroporto Internacional de Penang","Malásia"],
  ["CGK","Jacarta","Aeroporto Internacional Soekarno-Hatta","Indonésia"],
  ["DPS","Bali","Aeroporto Internacional Ngurah Rai","Indonésia"],
  ["SUB","Surabaya","Aeroporto Internacional Juanda","Indonésia"],
  ["MES","Medan","Aeroporto Internacional Kualanamu","Indonésia"],
  ["MNL","Manila","Aeroporto Internacional Ninoy Aquino","Filipinas"],
  ["CEB","Cebu","Aeroporto Internacional Mactan-Cebu","Filipinas"],
  ["SGN","Ho Chi Minh","Aeroporto Internacional Tan Son Nhat","Vietnã"],
  ["HAN","Hanói","Aeroporto Internacional Noi Bai","Vietnã"],
  ["DAD","Da Nang","Aeroporto Internacional de Da Nang","Vietnã"],
  ["REP","Siem Reap","Aeroporto Internacional de Siem Reap","Camboja"],
  ["PNH","Phnom Penh","Aeroporto Internacional de Phnom Penh","Camboja"],
  ["VTE","Vientiane","Aeroporto Internacional de Wattay","Laos"],
  ["RGN","Yangon","Aeroporto Internacional de Yangon","Myanmar"],
  ["CMB","Colombo","Aeroporto Internacional Bandaranaike","Sri Lanka"],
  ["KTM","Katmandu","Aeroporto Internacional Tribhuvan","Nepal"],
  ["DAC","Daca","Aeroporto Internacional Shahjalal","Bangladesh"],
  ["KHI","Karachi","Aeroporto Internacional Jinnah","Paquistão"],
  ["LHE","Lahore","Aeroporto Internacional Allama Iqbal","Paquistão"],
  ["ISB","Islamabad","Aeroporto Internacional de Islamabad","Paquistão"],
  ["TAS","Tashkent","Aeroporto Internacional de Tashkent","Uzbequistão"],
  ["ALA","Almaty","Aeroporto Internacional de Almaty","Cazaquistão"],
  ["NQZ","Astana","Aeroporto Internacional de Nursultan","Cazaquistão"],
  ["TBS","Tbilisi","Aeroporto Internacional de Tbilisi","Geórgia"],
  ["EVN","Yerevan","Aeroporto Internacional Zvartnots","Armênia"],
  ["GYD","Baku","Aeroporto Internacional Heydar Aliyev","Azerbaijão"],
  ["ULN","Ulaanbaatar","Aeroporto Internacional de Ulaanbaatar","Mongólia"],

  // ── Oceania ───────────────────────────────────────────────────────────────
  ["SYD","Sydney","Aeroporto Internacional de Kingsford Smith","Austrália"],
  ["MEL","Melbourne","Aeroporto Internacional de Melbourne","Austrália"],
  ["BNE","Brisbane","Aeroporto Internacional de Brisbane","Austrália"],
  ["PER","Perth","Aeroporto Internacional de Perth","Austrália"],
  ["ADL","Adelaide","Aeroporto Internacional de Adelaide","Austrália"],
  ["CBR","Canberra","Aeroporto de Canberra","Austrália"],
  ["OOL","Gold Coast","Aeroporto de Gold Coast","Austrália"],
  ["CNS","Cairns","Aeroporto Internacional de Cairns","Austrália"],
  ["DRW","Darwin","Aeroporto Internacional de Darwin","Austrália"],
  ["HBA","Hobart","Aeroporto de Hobart","Austrália"],
  ["AKL","Auckland","Aeroporto Internacional de Auckland","Nova Zelândia"],
  ["CHC","Christchurch","Aeroporto Internacional de Christchurch","Nova Zelândia"],
  ["WLG","Wellington","Aeroporto Internacional de Wellington","Nova Zelândia"],
  ["ZQN","Queenstown","Aeroporto de Queenstown","Nova Zelândia"],
  ["NAN","Nadi","Aeroporto Internacional de Nadi","Fiji"],
  ["PPT","Papeete","Aeroporto Internacional de Tahiti-Faa'a","Polinésia Francesa"],
  ["APW","Apia","Aeroporto de Faleolo","Samoa"],
  ["TBU","Nukualofa","Aeroporto Internacional Fua'amotu","Tonga"],
  ["HIR","Honiara","Aeroporto Internacional Henderson","Ilhas Salomão"],
  ["POM","Port Moresby","Aeroporto Internacional Jackson","Papua Nova Guiné"],
  ["SUV","Suva","Aeroporto Internacional de Nausori","Fiji"],
  ["GUM","Guam","Aeroporto Internacional A.B. Won Pat","Guam"],

  // ── África ────────────────────────────────────────────────────────────────
  ["JNB","Joanesburgo","Aeroporto Internacional O.R. Tambo","África do Sul"],
  ["CPT","Cidade do Cabo","Aeroporto Internacional de Cape Town","África do Sul"],
  ["DUR","Durban","Aeroporto Internacional King Shaka","África do Sul"],
  ["PLZ","Port Elizabeth","Aeroporto Internacional Nelson Mandela Bay","África do Sul"],
  ["CAI","Cairo","Aeroporto Internacional do Cairo","Egito"],
  ["HRG","Hurghada","Aeroporto Internacional de Hurghada","Egito"],
  ["SSH","Sharm el-Sheikh","Aeroporto Internacional de Sharm el-Sheikh","Egito"],
  ["LXR","Luxor","Aeroporto Internacional de Luxor","Egito"],
  ["CMN","Casablanca","Aeroporto Internacional Mohammed V","Marrocos"],
  ["RAK","Marrakech","Aeroporto Menara","Marrocos"],
  ["TNG","Tânger","Aeroporto Internacional Ibn Battouta","Marrocos"],
  ["FEZ","Fez","Aeroporto de Fez-Saïs","Marrocos"],
  ["ALG","Argel","Aeroporto Internacional Houari Boumedienne","Argélia"],
  ["TUN","Tunis","Aeroporto Internacional Carthage","Tunísia"],
  ["TIP","Trípoli","Aeroporto Internacional de Trípoli","Líbia"],
  ["ADD","Adis Abeba","Aeroporto Internacional Bole","Etiópia"],
  ["NBO","Nairóbi","Aeroporto Internacional Jomo Kenyatta","Quênia"],
  ["MBA","Mombasa","Aeroporto Internacional Moi","Quênia"],
  ["DAR","Dar es Salaam","Aeroporto Internacional Julius Nyerere","Tanzânia"],
  ["JRO","Kilimanjaro","Aeroporto Internacional do Kilimanjaro","Tanzânia"],
  ["ZNZ","Zanzibar","Aeroporto de Zanzibar","Tanzânia"],
  ["EBB","Kampala","Aeroporto Internacional Entebbe","Uganda"],
  ["KGL","Kigali","Aeroporto Internacional de Kigali","Ruanda"],
  ["LOS","Lagos","Aeroporto Internacional Murtala Muhammed","Nigéria"],
  ["ABV","Abuja","Aeroporto Internacional Nnamdi Azikiwe","Nigéria"],
  ["ACC","Acra","Aeroporto Internacional Kotoka","Gana"],
  ["ABJ","Abidjan","Aeroporto Internacional Félix Houphouët-Boigny","Costa do Marfim"],
  ["DKR","Dakar","Aeroporto Internacional Blaise Diagne","Senegal"],
  ["BKO","Bamako","Aeroporto Internacional Modibo Keïta","Mali"],
  ["OUA","Uagadugu","Aeroporto Internacional de Uagadugu","Burkina Faso"],
  ["COO","Cotonou","Aeroporto Internacional de Cadjehoun","Benin"],
  ["LFW","Lomé","Aeroporto Internacional de Lomé","Togo"],
  ["DLA","Douala","Aeroporto Internacional de Douala","Camarões"],
  ["NSI","Yaundê","Aeroporto Internacional de Nsimalen","Camarões"],
  ["LBV","Libreville","Aeroporto Internacional Léon-Mba","Gabão"],
  ["BZV","Brazzaville","Aeroporto Internacional Maya-Maya","Congo"],
  ["FIH","Kinshasa","Aeroporto Internacional de Ndjili","RD Congo"],
  ["FBM","Lubumbashi","Aeroporto Internacional de Lubumbashi","RD Congo"],
  ["LAD","Luanda","Aeroporto Internacional de Luanda","Angola"],
  ["MPM","Maputo","Aeroporto Internacional de Maputo","Moçambique"],
  ["BEW","Beira","Aeroporto da Beira","Moçambique"],
  ["VNX","Vilankulo","Aeroporto de Vilankulo","Moçambique"],
  ["SEZ","Mahe","Aeroporto Internacional de Seychelles","Seychelles"],
  ["MRU","Port Louis","Aeroporto Internacional Sir Seewoosagur Ramgoolam","Maurício"],
  ["RUN","Saint-Denis","Aeroporto Internacional Roland Garros","Reunião"],
  ["TNR","Antananarivo","Aeroporto Internacional Ivato","Madagascar"],
  ["HAH","Moroni","Aeroporto Internacional Prince Said Ibrahim","Comores"],
  ["WDH","Windhoek","Aeroporto Internacional Hosea Kutako","Namíbia"],
  ["GBE","Gaborone","Aeroporto Internacional de Gaborone","Botsuana"],
  ["HRE","Harare","Aeroporto Internacional de Harare","Zimbábue"],
  ["VFA","Victoria Falls","Aeroporto de Victoria Falls","Zimbábue"],
  ["LUN","Lusaka","Aeroporto Internacional Kenneth Kaunda","Zâmbia"],
  ["LLW","Lilongwe","Aeroporto Internacional de Lilongwe","Malawi"],
  ["BJL","Banjul","Aeroporto Internacional Banjul","Gâmbia"],
  ["OXB","Bissau","Aeroporto Internacional Osvaldo Vieira","Guiné-Bissau"],
  ["CKY","Conacri","Aeroporto Internacional de Gbessia","Guiné"],
  ["FNA","Freetown","Aeroporto Internacional Lungi","Serra Leoa"],
  ["ROB","Monróvia","Aeroporto Internacional Roberts","Libéria"],
  ["ABJ","Abidjan","Aeroporto Internacional Félix Houphouët-Boigny","Costa do Marfim"],
];

// Formata para exibição: "Nome do Aeroporto (IATA)"
function formatAirport(a) {
  return `${a[1]} (${a[0]})`;
}

// Busca por código IATA, cidade, nome do aeroporto ou país
function searchAirports(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  return AIRPORTS.filter(a => {
    const iata    = a[0].toLowerCase();
    const city    = a[1].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    const name    = a[2].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    const country = a[3].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return iata.startsWith(q) || city.includes(q) || name.includes(q) || country.includes(q);
  }).slice(0, 8);
}

// Cria o autocomplete num input
function initAirportAutocomplete(inputId) {
  const input = document.getElementById(inputId);
  if (!input) return;

  // Container wrapper
  const wrapper = document.createElement('div');
  wrapper.style.position = 'relative';
  input.parentNode.insertBefore(wrapper, input);
  wrapper.appendChild(input);

  // Dropdown
  const dropdown = document.createElement('ul');
  dropdown.className = 'airport-dropdown';
  wrapper.appendChild(dropdown);

  let activeIndex = -1;

  function showDropdown(results) {
    dropdown.innerHTML = '';
    activeIndex = -1;
    if (!results.length) { dropdown.style.display = 'none'; return; }

    results.forEach((airport, i) => {
      const li = document.createElement('li');
      const label = formatAirport(airport);
      li.innerHTML = `
        <span class="airport-iata">${airport[0]}</span>
        <span class="airport-info">
          <span class="airport-city">${airport[1]}</span>
          <span class="airport-name">${airport[2]}</span>
        </span>
        <span class="airport-country">${airport[3]}</span>
      `;
      li.addEventListener('mousedown', (e) => {
        e.preventDefault();
        input.value = label;
        dropdown.style.display = 'none';
      });
      dropdown.appendChild(li);
    });
    dropdown.style.display = 'block';
  }

  input.addEventListener('input', () => {
    showDropdown(searchAirports(input.value));
  });

  input.addEventListener('keydown', (e) => {
    const items = dropdown.querySelectorAll('li');
    if (!items.length) return;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      activeIndex = Math.min(activeIndex + 1, items.length - 1);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      activeIndex = Math.max(activeIndex - 1, 0);
    } else if (e.key === 'Enter' && activeIndex >= 0) {
      e.preventDefault();
      items[activeIndex].dispatchEvent(new Event('mousedown'));
      return;
    } else if (e.key === 'Escape') {
      dropdown.style.display = 'none';
      return;
    }
    items.forEach((li, i) => li.classList.toggle('active', i === activeIndex));
  });

  input.addEventListener('blur', () => {
    setTimeout(() => { dropdown.style.display = 'none'; }, 150);
  });

  input.addEventListener('focus', () => {
    if (input.value.length >= 2) showDropdown(searchAirports(input.value));
  });
}

// Inicializa em todos os campos de aeroporto
document.addEventListener('DOMContentLoaded', () => {
  ['origem_ida','destino_ida','origem_volta','destino_volta'].forEach(initAirportAutocomplete);
});